# This file was generated by GoReleaser. DO NOT EDIT.
cask "vybava" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "74382e0b3192f4571baa2b5cb5566dda218171e4a85c6ecbcb4785ceeffe85ac"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
    on_intel do
      sha256 "2ff421e5bdb2178d4ffe8201a1b8989f8f925f8926c98517f2b3c99492ba0030"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
  end
  on_linux do
    on_arm do
      sha256 "43b1e9a4c08a30b98ca38313a946f4f1790cf468262f81a5a5989520c5ecbea4"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
    on_intel do
      sha256 "8af51525385685670ba9e237c245b264b64a4392c74ee15a3158d2cf5c181e0d"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
  end

  name "vybava"
  desc "Portable engineering tools, agent skills, and diagnostics for every project"
  homepage "https://github.com/FixIt-Technologies/vybava"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vybava"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vybava"]
    end
  end

  # No zap stanza required
end
