# This file was generated by GoReleaser. DO NOT EDIT.
cask "vybava" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "0c29c3e3c122f86f5870664695d8201f33bb5336bee18a04ff52a1778218b0aa"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
    on_intel do
      sha256 "69b3a6ed3535e98bfb281d19169a610a4ce4336823bd182f901a57cb5206cc5e"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
  end
  on_linux do
    on_arm do
      sha256 "9638411d7149044e2cbc66abb789388e242799f53f0dc1573f60e4c62009b913"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
    on_intel do
      sha256 "611ea7bbe16b57d973b744e3e8cdb44bed7300d37b172dcecbab79262630f6d5"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/"
    end
  end

  name "vybava"
  desc "Portable engineering tools, agent skills, and diagnostics for every project"
  homepage "https://github.com/FixIt-Technologies/vybava"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vybava"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vybava"]
    end
  end

  # No zap stanza required
end
