# This file was generated by GoReleaser. DO NOT EDIT.
cask "vybava" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      super("https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}", name, version, **meta)
    end

    def download_url
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def parse_url_pattern
      pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid private GitHub release URL" unless @url =~ pattern

      _, @owner, @repo, @tag, @filename = *@url.match(pattern)
    end

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required" unless @github_token

      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |asset| asset["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Release asset not found" }
    end
  end

  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1d1e49e1e3ad70a61f2620d22f613d11ce7ac14653f69553d93cd5a51fe678ff"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "c58431d44636651a5582d6596a3f32b6134f082f64da21c63355b90c69c7837a"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "3e7333bd41d5a10745afe28e8f95b714788722ecdd2b1ab5592fbc42d64f2bb2"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "202e259baf3273f08fe6977ef8ff64382501f24258a1ed580d897dad579f1a04"
      url "https://github.com/FixIt-Technologies/vybava/releases/download/v#{version}/vybava_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FixIt-Technologies/vybava/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "vybava"
  desc "Portable engineering tools, agent skills, and diagnostics for every project"
  homepage "https://github.com/FixIt-Technologies/vybava"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vybava"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vybava"]
    end
  end

  # No zap stanza required

end
